### ISSUE TITLE
ipynb isnt properly set up as submodule

### ISSUE THREAD

**Issue by clayjohn** [CalebJohn/infinitemonkeytheorem#1]
I tried cloning the repo from master and it didnt include ipynb, even on here ipynb appears as a folder but you cant click on it.

**Comment by CalebJohn** [comment]
I don't know what you mean by ipynb, is that a folder?

**Comment by clayjohn** [comment]
Yea, its a folder in the plugins directory. Its for using the jupyter notebooks I think.

**Comment by CalebJohn** [comment]
I ditched the plugins, we're going dependency free.
